version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
#    ports:
#      - "15672:15672"
    expose:
      - 5672
  translator:
    build: src/translator
    env_file: .env
    volumes:
      - "./src/translator:/app"
      - "./i18n/:/i18n"
    environment:
      RABBIT_URL: "amqp://rabbitmq:rabbitmq@rabbit"
    depends_on:
      - rabbit
  store:
    build: src/store
    env_file: .env
    volumes:
      - "./src/store:/app"
    environment:
      MONGO_URL: "mongodb://mongo:27017/fsbot"
      RABBIT_URL: "amqp://rabbitmq:rabbitmq@rabbit"
    depends_on:
      - rabbit
  front:
    build: src/front
    env_file: .env
    volumes:
      - "./src/front:/app"
    environment:
      MONGO_URL: "mongodb://mongo:27017/fsbot"
      RABBIT_URL: "amqp://rabbitmq:rabbitmq@rabbit"
    depends_on:
      - rabbit
  mongo:
    image: 'mongo'
    volumes:
      - "./data/mongo:/data/db"
