version: '3'
services:
  front:
    build: src/front
    env_file: .env
    volumes:
      - "./src/front:/app"
      - "./i18n/:/i18n"
    environment:
      MONGO_URL: "mongodb://mongo:27017/fsbot"
    depends_on:
      - mongo
  mongo:
    image: 'mongo'
    volumes:
      - "./data/mongo:/data/db"
